channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gzip
  - pytools
  - pysam
  - rsync
  - snakemake=7.32.4
  - umi_tools=1.1.5
  - bedtools=2.31.1
  - cutadapt=4.8
  - bowtie2=2.5.4
  - r-base=4.3.3
  - fastqc=0.12.1
  - samtools=1.20
  - ucsc-bedgraphtobigwig
  - subread
