channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - os
  - glob
  - re
  - subprocess
  - gzip
  - random
  - pysam
  - unzip
  - umi_tools=0.5.4
  - bedtools=2.29.2
  - cutadapt=2.3
  - bowtie2=2.3.2
  - samtools
  - subread=2.0.6
  - r-base=4.0.3
