# ===== Config file for genome parameters ======================================


## GENERAL PARAMETERS ##

# Path to bowtie2 index
INDEX:
    "/beevol/home/rbilab/ref/indices/bowtie2/mouse/GRCm38/GRCm38"


# Path to chrom.sizes file
CHROMS:
    "/beevol/home/rbilab/ref/genome/mouse/GRCm38/dna/Mus_musculus.GRCm38.dna.primary_assembly.UCSC.fa.fai"


# Path to GTF file
GTF:
    "/beevol/home/rbilab/ref/annotation/mouse/GRCm38/gtf/Mus_musculus.GRCm38.95.gtf"


# Path to bed file containing regions to use for downstream analysis.
# Reads not overlapping these regions will be removed. Since lower quality
# mNET-seq libraries will have more reads aligning in intergenic regions,
# we decided to only use reads that fall with +/-5 kb of a protein coding
# gene.
GENES:
    "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_4_-5kb_+5kb.bed.gz"


# Path to bed file containing regions to exclude from analysis. Reads
# overlapping these regions will be removed. Since lower quality mNET-seq
# libraries will have more reads aligning to snoRNAs, we decided to remove
# these reads before performing downstream analysis
MASK:
    "/beevol/home/sheridanr/ref/gene_lists/GRCm38/base_lists/GRCm38_snoRNAs.bed.gz"


# Regions to use for subsampling reads
# The samples in each group will be subsampled to the same read depth for
# the provided regions. These files should be bed files with the regions
# containing the regions to use for each gene.
GENE_SUBSAMPLE_BEDS:
    tss:  "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_TSS_+500bp.bed.gz"
    body: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_4_+500bp_pAS.bed.gz"
    gene: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/base_lists/GRCm38_4_TSS_pAS.bed.gz"


# Bed files to use for counting mNET-seq reads, the resulting output files
# can be used to generate metaplots. For each bed file, provide a unique
# name to use for naming output files.
META_BEDS:
    5-TSS-100bp:   "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_TSS_+100bp.bed.gz"
    5-100bp-300bp: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_+100bp_+300bp.bed.gz"
    5-300bp-500bp: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_+300bp_+500bp.bed.gz"
    5-500bp-1kb:   "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_+500bp_+1kb.bed.gz"
    4-200bp:       "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_windows/GRCm38_4_TSS_pAS_200bp.bed.gz"
    5-10bp:        "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_windows/GRCm38_5_-2kb_+2kb_10bp.bed.gz"
    3-50bp:        "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_windows/GRCm38_3_-5kb_+5kb_50bp.bed.gz"
    5ss-wins:      "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_5ss_50bp_1bp.bed.gz"
    exons:         "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_exons.bed.gz"
    introns:       "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_introns.bed.gz"


# Bed file containing gene coordinates to use for generating matrices for
# metaplots
META_MATRIX_BED:
    "/beevol/home/sheridanr/ref/gene_lists/GRCm38/base_lists/GRCm38_4_TSS_pAS.bed.gz"


# Regions to use for testing output files from per-gene subsampling. This
# will double check that each gene in the provided bed file has the same
# number of overlapping reads for each sample in the subsampling group. This
# list cannot include overlapping genes, since read counts for
# overlapping genes may differ between samples in the subsampling group.
TEST_GENES: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/base_lists/GRCm38_0ksep.bed.gz"



## PAUSING PARAMETERS ##

# Path to bed file containing regions to use for identifying pauses.
PAUSE_GENES:
    "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_4_TSS_+5kb.bed.gz"


# Path to bed file containing regions to exclude from analysis. Pauses
# overlapping these regions will be removed. 
PAUSE_MASK:
    - "/beevol/home/sheridanr/ref/gene_lists/GRCm38/base_lists/GRCm38_snoRNAs.bed.gz"
    - "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_5ss_2bp.bed.gz"
    - "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_3ss_2bp.bed.gz"


# Bed files to use for counting pauses, the resulting output files
# can be used to generate metaplots. For each bed file, provide a unique
# name to use for naming output files.
PAUSE_META_BEDS:
    5-TSS-100bp:   "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_TSS_+100bp.bed.gz"
    5-100bp-300bp: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_+100bp_+300bp.bed.gz"
    5-300bp-500bp: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_+300bp_+500bp.bed.gz"
    5-500bp-1kb:   "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_+500bp_+1kb.bed.gz"
    4-200bp:       "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_windows/GRCm38_4_TSS_pAS_200bp.bed.gz"
    5-10bp:        "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_windows/GRCm38_5_-2kb_+2kb_10bp.bed.gz"
    3-50bp:        "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_windows/GRCm38_3_-5kb_+5kb_50bp.bed.gz"
    exons:         "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_exons.bed.gz"
    introns:       "/beevol/home/sheridanr/ref/gene_lists/GRCm38/splicing_lists/GRCm38_introns.bed.gz"



## PLOTTING PARAMETERS ##

ref_dir:           "/beevol/home/sheridanr/ref"                                         # Reference directory
list_dir:          "gene_lists/GRCm38"                                                  # Gene list directory from ref_dir path
genome:            "genome/GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.UCSC.fa.fai" # Chromosome sizes
fasta:             "genome/GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.UCSC.fa"     # Fasta for pulling sequences
genes_all:         "base_lists/GRCm38_HCT116_genes.bed.gz"
genes_5:           "base_lists/GRCm38_5ksep.bed.gz"                                     # Gene list for 5' metaplots
genes_3:           "base_lists/GRCm38_5ksep.bed.gz"                                     # Gene list for 3' metaplots
genes_zone:        "base_lists/GRCm38_2ksep.bed.gz"                                     # Gene list for pausing zone plots
genes_pause:       "base_lists/GRCm38_5ksep.bed.gz"                                     # Gene list for pause metaplots and sequence logos
exons:             "/splicing_lists/GRCm38_exons.bed.gz"                                # Bed file containing exon coordinates
trxn_info:         "/base_lists/base_gene_files/GRCm38_transcripts.bed.gz"              # Bed file containing transcript info to use for filtering exons

pause_regions:
    TSS:  "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_5_TSS_+500bp.bed.gz"
    body: "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_4_+500bp_pAS.bed.gz"
    pAS:  "/beevol/home/sheridanr/ref/gene_lists/GRCm38/gene_regions/GRCm38_3_pAS_+5kb.bed.gz"


