#===== Config file for filtering and aligning mNET-seq reads ===================


# Docker container to use for pipeline
CONTAINER:
    "docker://rmsheridan/find-pauses:v5"


# Directory to store results
RESULTS:
    "results"


# Should intermediate file be kept
KEEP_INTERMEDIATE_FILES:
    False


# Base memory to request for each rule
# * The acutal amount requested will be higher for rules that generally
#   require more memory
# * A value of 8 will result in rules requesting between 8Gb - 32Gb of
#   memory
MEMORY:
    16


# Path to bowtie2 index
INDEX:
    "/beevol/home/rbilab/ref/indices/bowtie2/human/GRCh38/GRCh38"


# Path to chrom.sizes file
CHROMS:
    "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa.fai"


# Path to GTF file
GTF:
    "/beevol/home/rbilab/ref/annotation/human/GRCh38/gtf/Homo_sapiens.GRCh38.95.gtf"


# Path to bed file containing regions to use for downstream analysis.
# Reads not overlapping these regions will be removed. Since lower quality
# mNET-seq libraries will have more reads aligning in intergenic regions,
# we decided to only use reads that fall with +/-5 kb of a protein coding
# gene.
GENES:
    "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_4_-5kb_+5kb.bed.gz"


# Path to bed file containing regions to exclude from analysis. Reads
# overlapping these regions will be removed. Since lower quality mNET-seq
# libraries will have more reads aligning to snoRNAs, we decided to remove
# these reads before performing downstream analysis
MASK:
    "/beevol/home/sheridanr/ref/gene_lists/GRCh38/base_lists/GRCh38_snoRNAs.bed.gz"


# Regions to use for subsampling reads
# The samples in each group will be subsampled to the same read depth for
# the provided regions. These files should be bed files with the regions
# containing the regions to use for each gene.
GENE_SUBSAMPLE_BEDS:
    tss:  "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_5_TSS_+500bp.bed.gz"
    body: "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_4_+500bp_pAS.bed.gz"
    gene: "/beevol/home/sheridanr/ref/gene_lists/GRCh38/base_lists/GRCh38_4_TSS_pAS.bed.gz"


# Regions to use for testing output files from per-gene subsampling. This
# will double check that each gene in the provided bed file has the same
# number of overlapping reads for each sample in the subsampling group. This
# list cannot include overlapping genes, since read counts for
# overlapping genes may differ between samples in the subsampling group.
TEST_GENES: "/beevol/home/sheridanr/ref/gene_lists/GRCh38/base_lists/GRCh38_0ksep.bed.gz"


# Bed files to use for counting mNET-seq reads, the resulting output files
# can be used to generate metaplots. For each bed file, provide a unique
# name to use for naming output files.
META_BEDS:
    5-TSS-100bp:   "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_5_TSS_+100bp.bed.gz"
    5-100bp-300bp: "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_5_+100bp_+300bp.bed.gz"
    5-300bp-500bp: "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_5_+300bp_+500bp.bed.gz"
    5-500bp-1kb:   "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_regions/GRCh38_5_+500bp_+1kb.bed.gz"
    4-200bp:       "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_windows/GRCh38_4_TSS_pAS_200bp.bed.gz"
    5-10bp:        "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_windows/GRCh38_5_-2kb_+2kb_10bp.bed.gz"
    3-50bp:        "/beevol/home/sheridanr/ref/gene_lists/GRCh38/gene_windows/GRCh38_3_-5kb_+5kb_50bp.bed.gz"
    5ss-wins:      "/beevol/home/sheridanr/ref/gene_lists/GRCh38/splicing_lists/GRCh38_5ss_50bp_1bp.bed.gz"
    exons:         "/beevol/home/sheridanr/ref/gene_lists/GRCh38/splicing_lists/GRCh38_exons.bed.gz"
    introns:       "/beevol/home/sheridanr/ref/gene_lists/GRCh38/splicing_lists/GRCh38_introns.bed.gz"


## Additional parameters for various processing steps
# Cutadapt
# --pair-filter=first - read filtering decisions are made based solely on R1
# --dicard-untrimmed  - remove reads that do not contain an adapter
# --minimum-length    - remove reads that are shorter than given value
# -O                  - minimum overlap to trim adapter
# -a                  - adapter sequence for R1
# -A                  - adapter sequence for R2
#
# umi tools
# --method unique     - only remove read if the UMI sequence is an exact match
# --read-length       - use read length when removing duplicates
#
# featureCounts
# -s 0                - strandedness for read assignment; 0, unstranded
# -t gene             - feature type for counting
# -O                  - count if aligned to multiple features
CMD_PARAMS:
    cutadapt:      " --pair-filter=first --discard-untrimmed --minimum-length 15 -O 10 -a 'AACTGTAGGCACCATCAAT' -A 'GATCGTCGGACTGTAGAACTCTGAAC' "
    umi_pattern:   "NNNNNNNNNNNN"
    umi_tools:     " --method unique --read-length "
    featureCounts: " --extraAttributes 'gene_name,gene_biotype' -s 0 -t gene -O "



